name: build
on:
  push:
    tags:
      - 'release/*'
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    name: build-and-push
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: aws configure
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
      - name: login ecr
        id: ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: build and push
        env:
          ECR_URI: '328625957455.dkr.ecr.ap-northeast-1.amazonaws.com/simple-sqsd'
        run: |
          IMAGE_TAG=$(echo ${{ github.ref }} | sed -e "s@refs/tags/release/@@g")
          docker build -t ${{ steps.ecr.outputs.registry }}/$ECR_URI:$IMAGE_TAG .
          docker push ${{ steps.ecr.outputs.registry }}/$ECR_URI:$IMAGE_TAG
